### PR TITLE
Merging tokenising step

### PR DESCRIPTION
**Pull request by ThatoJadezweni**
I think this is enough for now tokenising wise. Try to break it.

### CODE REVIEW

**Comment by ThatoJadezweni** [comment]
also afterwards remove the "stuff.txt" file please

**Comment by ThatoJadezweni** [comment]
should we develop tests for each phase? 
or only test the end result - the compiled result?

**Comment by ThatoJadezweni** [comment]
delete the tokeniser branch afterwards

**Comment by sthenyandeni** [comment]
I will have a look at the changes and then proceed with the PR by tomorrow

**Review by sthenyandeni — APPROVED** [review]
I have reviewed the code and tested it with some sample code files and the results are satisfactory

**Comment by ThatoJadezweni** [comment]
the context-free grammar is set to be completed by the end of today. be sure to be ready for briefing of it.

**Comment by sthenyandeni** [comment]
Let's have the briefing around 17:00

**Pull request merged**
